    version: '2'
    services:
      kcptun:
          image: kcptun_docker:arm
        ports:
          - "9527:9527"
        environment:
          - SERVER_ADD=*.*.*.*:8388
        restart: always
